// Sample data for the application
export const initialData = {
  projects: [
    {
      id: "p1",
      name: "Website Redesign",
      description: "Redesign the company website with modern UI/UX principles",
      startDate: "2023-05-01",
      endDate: "2023-06-30",
      createdAt: "2023-04-15T10:00:00Z",
    },
    {
      id: "p2",
      name: "Mobile App Development",
      description: "Develop a mobile app for both iOS and Android platforms",
      startDate: "2023-06-01",
      endDate: "2023-09-30",
      createdAt: "2023-05-20T14:30:00Z",
    },
    {
      id: "p3",
      name: "Marketing Campaign",
      description: "Plan and execute Q3 marketing campaign",
      startDate: "2023-07-01",
      endDate: "2023-09-30",
      createdAt: "2023-06-15T09:45:00Z",
    },
  ],

  teamMembers: [
    {
      id: "tm1",
      name: "John Doe",
      email: "john.doe@example.com",
      phone: "555-123-4567",
      role: "Frontend Developer",
      createdAt: "2023-01-10T08:00:00Z",
    },
    {
      id: "tm2",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      phone: "555-987-6543",
      role: "UI/UX Designer",
      createdAt: "2023-01-15T10:30:00Z",
    },
    {
      id: "tm3",
      name: "Mike Johnson",
      email: "mike.johnson@example.com",
      phone: "555-456-7890",
      role: "Backend Developer",
      createdAt: "2023-02-05T09:15:00Z",
    },
    {
      id: "tm4",
      name: "Sarah Williams",
      email: "sarah.williams@example.com",
      phone: "555-789-0123",
      role: "Project Manager",
      createdAt: "2023-02-10T11:45:00Z",
    },
  ],

  tasks: [
    {
      id: "t1",
      title: "Design Homepage Mockup",
      description: "Create mockups for the new homepage design",
      projectId: "p1",
      assigneeId: "tm2",
      dueDate: "2023-05-15",
      status: "approved",
      progress: 100,
      createdBy: "manager",
      createdAt: "2023-05-01T09:00:00Z",
    },
    {
      id: "t2",
      title: "Implement Homepage Frontend",
      description: "Convert the approved mockups to HTML/CSS/JS",
      projectId: "p1",
      assigneeId: "tm1",
      dueDate: "2023-05-30",
      status: "approved",
      progress: 75,
      createdBy: "manager",
      createdAt: "2023-05-16T10:30:00Z",
    },
    {
      id: "t3",
      title: "Setup API Endpoints",
      description: "Create necessary API endpoints for the mobile app",
      projectId: "p2",
      assigneeId: "tm3",
      dueDate: "2023-06-15",
      status: "approved",
      progress: 50,
      createdBy: "manager",
      createdAt: "2023-06-01T14:00:00Z",
    },
    {
      id: "t4",
      title: "Create Social Media Content",
      description: "Prepare content for social media posts for the marketing campaign",
      projectId: "p3",
      assigneeId: "tm4",
      dueDate: "2023-07-15",
      status: "approved",
      progress: 25,
      createdBy: "manager",
      createdAt: "2023-07-01T11:15:00Z",
    },
    {
      id: "t5",
      title: "Optimize Database Queries",
      description: "Improve performance of database queries for the mobile app",
      projectId: "p2",
      assigneeId: null,
      suggestedBy: "tm3",
      dueDate: "2023-07-30",
      status: "pending",
      progress: 0,
      createdBy: "team-member",
      createdAt: "2023-07-10T16:45:00Z",
    },
    {
      id: "t6",
      title: "User Testing",
      description: "Conduct user testing sessions for the new website design",
      projectId: "p1",
      assigneeId: null,
      suggestedBy: "tm2",
      dueDate: "2023-06-20",
      status: "pending",
      progress: 0,
      createdBy: "team-member",
      createdAt: "2023-06-10T13:30:00Z",
    },
  ],
}
